Introducing and handling a termination message
ie3-institute/simonaAPI pull request #16
Opened 2022-01-11 17:47 UTC by sebastian-peter

Resolves #5

Plus enabling tests w/ gradle and Jenkins
Plus implementation of tests for ExtSimulation

2022-01-12 13:17 UTC, sebastian-peter commented on src/test/groovy/edu/ie3/simona/api/simulation/ExtSimulationSpec.groovy
> +    class UnknownMessage implements ExtSimMessage {}
@sonatype-lift ignore

2022-01-14 08:39 UTC, ckittl requested changes
Generally looks good to me!

However, only point of discussion is, if we wouldn't like to see the termination as a pro-active step rather then "uh, someone else has terminated, better do that, too". In that regard: Do we need a feedback about successful termination?

2022-01-14 08:55 UTC, ckittl commented
... an please add your contributions to CHANGELOG.md

2022-01-14 11:30 UTC, sebastian-peter commented
@ckittl introduced indication whether main simulation was successful, and a `TerminationCompleted` message that is sent back to main simulation when the termination process in ext sim has finished (as discussed)

2022-01-14 13:54 UTC, ckittl approved these changes

2022-01-14 13:55 UTC, merged