Enable init for primary data and result data
ie3-institute/simonaAPI pull request #168
Opened 2024-03-16 09:10 UTC by jo-bao

Resolves #167

2024-10-21 11:50 UTC, danielfeismann requested changes
Thanks for enhancing the API! I have some questions and points

2024-10-21 11:50 UTC, danielfeismann commented on src/test/groovy/edu/ie3/simona/api/data/results/ExtResultDataTest.groovy
> +        thrown RuntimeException
Given also the sonarqube / codacy issues it would be good to check for a specific exception type and maybe as well the exception message.

2024-10-21 11:50 UTC, danielfeismann commented on src/main/java/edu/ie3/simona/api/simulation/mapping/ExtEntityMapping.java
> +  public Map<String, UUID> getExtIdUuidMapping(String dataType) {
IdUuid and UuidID are very hard to distingues. Maybe Id2Uuid and Uuid2Id makes it a little bit easier?

2024-10-23 11:13 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/em/ontology/ProvideEmSetPointData.java
> +    long tick, Map<UUID, PValue> emData, Optional<Long> maybeNextTick)
PValue is an superclass of SValue, so it contains this case too.

2024-10-23 11:15 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/em/ExtEmData.java
> +  /** Provide primary data from an external simulation in one tick. */
Yes, sounds better!

2024-10-23 12:49 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/primarydata/ExtPrimaryData.java
> +    sendExtMsg(new ProvidePrimaryData(tick, primaryData, maybeNextTick));
Previous we used a json representation for the primary data. Now we switched to the value representation which can combine different types (e.g. HeatAndPValue).

2024-10-23 12:58 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/primarydata/ExtPrimaryDataSimulation.java
> - */
If I have a correct overview this interface is obsolete. I'll gonna delete it at all.

2024-10-23 13:29 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/simulation/ExtSimulation.java
> +                    .tick()); // this is blocking until processing of this tick has finished
Haha no!

2024-10-23 13:30 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/simulation/mapping/ExtEntityEntry.java
> +  public static final String EXT_RESULT_GRID = "result_grid";
Yes they are used in the mapping in Opsim

2024-10-23 14:32 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/results/ExtResultPackage.java
> +              .add(nodeResult.getvMag().subtract(Quantities.getQuantity(1.0, PU)));
For the use cases we only consider the deviation of the absolute value. I think the angle can be implemented easily afterwards.

2024-10-24 11:22 UTC, jo-bao commented on src/test/groovy/edu/ie3/simona/api/data/em/ExtEmDataTest.groovy
> +        actorSystem = null
I am only following the pattern of the ExtEvDataTest. Maybe we can simplify everything in another issue?

2024-10-24 11:22 UTC, jo-bao commented on src/test/groovy/edu/ie3/simona/api/data/em/ExtEmDataTest.groovy
> +        def extEmData = new ExtEmData(new TestEmDataFactory(), extEmDataMapping)
I am only following the pattern of the ExtEvDataTest. Maybe we can simplify everything in another issue?

2024-10-24 11:24 UTC, jo-bao commented on src/test/groovy/edu/ie3/simona/api/data/results/ExtResultDataTest.groovy
> +        thrown RuntimeException
I am only following the pattern of the ExtEvDataTest. Maybe we can introduce more service error messages in another issue?

2024-10-24 12:19 UTC, jo-bao commented on src/test/groovy/edu/ie3/simona/api/data/em/ExtEmDataTest.groovy
> +    )
Good idea!

2024-10-30 11:08 UTC, danielfeismann commented on src/test/groovy/edu/ie3/simona/api/data/results/ExtResultDataTest.groovy
> +        thrown RuntimeException
Yes, sure

2024-10-30 11:10 UTC, danielfeismann commented on src/main/java/edu/ie3/simona/api/data/results/ExtResultPackage.java
> +              .add(nodeResult.getvMag().subtract(Quantities.getQuantity(1.0, PU)));
Ok, but maybe we should 
- a) do it right from the beginning to avoid that later somebody will use it and asumes angles are included OR 
- b) at least give a comment that this isn't the case (plus maybe create the issue that this needs to be done)?

2024-11-07 09:23 UTC, staudtMarius requested changes
This looks good to me. I found some parts that could be improved.

2024-11-07 09:23 UTC, staudtMarius commented on src/main/java/edu/ie3/simona/api/simulation/mapping/ExtEntityMappingCsvSource.java
> +  }
You could use the `Factory.get` method here to build your `ExtentitEntry` instead of building it manually.

2024-11-07 09:23 UTC, staudtMarius commented on src/test/groovy/edu/ie3/simona/api/data/results/ExtResultPackageTest.groovy
> +    }
You could add a test for `getReactivePower` for both cases.

2024-11-08 21:35 UTC, sebastian-peter requested changes
Some points from my side for now

2024-11-08 21:35 UTC, sebastian-peter commented on build.gradle
> -
A bit pedantic from me, but please revert unnecessary change

2024-11-08 21:35 UTC, sebastian-peter commented on src/main/java/edu/ie3/simona/api/data/ExtDataPackage.java
For all `*Package` classes:

- Please find a different name, package has a fixed meaning in software projects. Maybe `*Container`, or something better.

For `*Package`, `DataQueueExtSimulationExtSimulator`, `ExtEntityMappingCsvSource` (?), maybe more:

- These classes seem not to be used by simonaAPI directly, but by the API projects on the "external side". Please consider moving these classes and re-using them by either
  - combining both "external API" projects (simosaik and simopsim) or
  - creating a third "external API" project that is a dependency to both simosaik and simopsim

2024-11-08 21:35 UTC, sebastian-peter commented on src/main/java/edu/ie3/simona/api/data/primarydata/ExtPrimaryData.java
> +                } catch (ConvertionException e) {
Missed this before, but I guess this is supposed to be `ConversionException`?

2024-11-15 09:48 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/data/primarydata/ExtPrimaryData.java
> +                } catch (ConvertionException e) {
Yes

2024-11-15 10:13 UTC, jo-bao commented on src/test/groovy/edu/ie3/simona/api/data/results/ExtResultPackageTest.groovy
> +    )
Yes, you're right!

2024-11-15 10:51 UTC, jo-bao commented on src/main/java/edu/ie3/simona/api/simulation/mapping/ExtEntityMappingCsvSource.java
> +  }
Oh, yes, thank you for this idea!

2024-11-22 08:04 UTC, staudtMarius requested changes
LGTM. Just one small point.

2024-11-27 09:35 UTC, staudtMarius requested changes
I have just one more comment on the `build.gradle`. Also one test seem to fail. Other then that, this looks good to me.

2024-11-27 09:39 UTC, jo-bao commented on build.gradle
> +  //implementation "ch.qos.logback:logback-classic:1.4.14"
Fair point

2024-11-27 13:34 UTC, staudtMarius submitted a review, later dismissed
LGTM.

2024-11-27 14:33 UTC, danielfeismann reviewed
LGTM :)

2024-11-27 14:34 UTC, danielfeismann submitted a review, later dismissed
LGTM :)

2024-11-28 09:47 UTC, sebastian-peter requested changes
Looks good overall.

There's a bunch of code smells that you could take care of before merging. Also, it'd be nice to have a test for `ExtEntityMappingCsvSource` imho, but that can also be done in a separate PR.

2024-11-28 15:45 UTC, sebastian-peter approved these changes
Let's go!

2024-11-28 17:59 UTC, merged