add documentation
ie3-institute/simonaAPI pull request #63
Opened 2022-08-01 11:06 UTC by t-ober

Resolves #59

2022-08-01 14:04 UTC, t-ober commented
Please carefully review the documentation to ensure that I did understand the stuff correctly.

2022-08-10 15:19 UTC, sebastian-peter requested changes
Thanks a lot for tackling this! It's something that has been in dire need for some time now.

Additionally to my comments, there's some classes
- `EvModel`
- `AllDepartedEvsResponse` (which we probably can agree on, has a terrible name)
- `ExtEvMessage`
- `ProvideCurrentPrices`
- ...

I can for sure help out with that if you're busy with other things :)

2022-10-16 17:22 UTC, sebastian-peter commented on src/main/java/edu/ie3/simona/api/data/ev/ExtEvData.java
> +  public List<EvModel> exchangeEvcsArrivalsAndDepartures(
Doesn't matter anymore because this is going to change soon anyway

2022-10-16 17:36 UTC, sebastian-peter commented on src/main/java/edu/ie3/simona/api/data/ev/ontology/EvcsMovementsMessage.java
> + * @param movements the movements which are communicated
This is a bug with sonatype, it's a param within a record

2022-10-16 17:43 UTC, sebastian-peter approved these changes

2022-10-16 17:44 UTC, merged